# Generated by Django 4.2.26 on 2025-11-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.CharField(max_length=100)),
                ('hausnummer', models.CharField(max_length=10)),
                ('plz', models.CharField(max_length=10)),
                ('ortsname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ausbildungsberuf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('beschreibung', models.TextField()),
                ('anforderungen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bewerber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('geburtsdatum', models.DateField()),
                ('geschlecht', models.CharField(max_length=10)),
                ('faehigkeiten_qualifikationen', models.TextField()),
                ('motivationsschreiben', models.TextField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Einsatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bewerber')),
            ],
        ),
        migrations.CreateModel(
            name='Kontaktdaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorwahl_telefonnummer', models.CharField(max_length=10)),
                ('telefonnummer', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Unternehmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ansprechpartner', models.CharField(max_length=100)),
                ('beschreibung', models.TextField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adresse')),
                ('kontaktdaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kontaktdaten')),
            ],
        ),
        migrations.CreateModel(
            name='UnternehmenAusbildungsplatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anforderungen_unternehmen', models.TextField()),
                ('startdatum', models.DateField()),
                ('enddatum', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adresse')),
                ('ausbildungsberuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ausbildungsberuf')),
                ('unternehmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unternehmen')),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_datum', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bewerber')),
                ('unternehmen_ausbildungsplatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unternehmenausbildungsplatz')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('bewertung_bewerber', models.TextField()),
                ('bewertung_unternehmen', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.einsatz')),
            ],
        ),
        migrations.AddField(
            model_name='einsatz',
            name='unternehmen_ausbildungsplatz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unternehmenausbildungsplatz'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='kontaktdaten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kontaktdaten'),
        ),
        migrations.AddField(
            model_name='ausbildungsberuf',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branche'),
        ),
        migrations.CreateModel(
            name='BewerberWunschberuf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausbildungsberuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ausbildungsberuf')),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bewerber')),
            ],
            options={
                'unique_together': {('bewerber', 'ausbildungsberuf')},
            },
        ),
    ]
