# Generated by Django 5.2.8 on 2025-11-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strasse', models.CharField(max_length=100)),
                ('hausnummer', models.CharField(max_length=10)),
                ('plz', models.CharField(max_length=5, verbose_name='PLZ')),
                ('ortsname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kontaktdaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorwahl_telefonnummer', models.CharField(max_length=10)),
                ('telefonnummer', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Bewerber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=100)),
                ('vorname', models.CharField(max_length=100)),
                ('geburtsdatum', models.DateField()),
                ('geschlecht', models.CharField(choices=[('m', 'Männlich'), ('w', 'Weiblich'), ('d', 'Divers')], max_length=10)),
                ('faehigkeiten_qualifikationen', models.TextField()),
                ('motivationsschreiben', models.TextField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adresse')),
                ('kontaktdaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kontaktdaten')),
            ],
        ),
        migrations.CreateModel(
            name='Ausbildungsberuf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(choices=[('fachinformatiker', 'Fachinformatiker*in'), ('it_systemelektroniker', 'IT-Systemelektroniker*in'), ('tiefbaufacharbeiter', 'Tiefbaufacharbeiter*in'), ('maurer', 'Maurer*in'), ('einzelhandelskaufmann', 'Kaufmann/-frau im Einzelhandel'), ('grosshandelskaufmann', 'Kaufmann/-frau im Großhandel'), ('pflegefachkraft', 'Pflegefachkraft'), ('medizinische_fachangestellte', 'Medizinische Fachangestellte*r'), ('steuerfachangestellte', 'Steuerfachangestellte*r'), ('versicherungs_kaufmann', 'Kaufmann/-frau für Versicherungen & Finanzen'), ('fachkraft_lagerlogistik', 'Fachkraft für Lagerlogistik'), ('berufskraftfahrer', 'Berufskraftfahrer*in')], max_length=100)),
                ('beschreibung', models.TextField()),
                ('anforderungen', models.TextField()),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.branche')),
            ],
        ),
        migrations.CreateModel(
            name='Einsatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatum', models.CharField(blank=True, max_length=5, null=True)),
                ('enddatum', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.CharField(choices=[('ausstehend', 'ausstehend'), ('aktiv', 'aktiv'), ('abgebrochen', 'abgebrochen'), ('abgeschlossen', 'abgeschlossen')], default='ausstehend', max_length=20)),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bewerber')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('bewertung_bewerber', models.TextField()),
                ('bewertung_unternehmen', models.TextField()),
                ('status', models.CharField(choices=[('ausstehend', 'ausstehend'), ('abgeschlossen', 'abgeschlossen')], max_length=20)),
                ('einsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.einsatz')),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matchingdatum', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('berechnet', 'berechnet'), ('vorgeschlagen', 'vorgeschlagen'), ('angenommen', 'angenommen'), ('abgelehnt', 'abgelehnt')], default='berechnet', max_length=20)),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='main.bewerber')),
            ],
        ),
        migrations.AddField(
            model_name='einsatz',
            name='matching',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.matching'),
        ),
        migrations.CreateModel(
            name='Unternehmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ansprechpartner', models.CharField(max_length=100)),
                ('beschreibung', models.TextField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adresse')),
                ('kontaktdaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kontaktdaten')),
            ],
        ),
        migrations.CreateModel(
            name='UnternehmenAusbildungsplatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anforderungen_unternehmen', models.TextField()),
                ('zeitraum', models.CharField(choices=[('q1', '01.08 – 31.10'), ('q2', '01.11 – 31.01'), ('q3', '01.02 – 30.04'), ('q4', '01.05 – 31.07')], default='q1', max_length=10)),
                ('status', models.CharField(choices=[('frei', 'Frei'), ('blockiert', 'Blockiert'), ('vergeben', 'Vergeben')], default='frei', max_length=20)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.adresse')),
                ('ausbildungsberuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ausbildungsberuf')),
                ('unternehmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.unternehmen')),
            ],
        ),
        migrations.AddField(
            model_name='matching',
            name='unternehmen_ausbildungsplatz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchings', to='main.unternehmenausbildungsplatz'),
        ),
        migrations.AddField(
            model_name='einsatz',
            name='unternehmen_ausbildungsplatz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unternehmenausbildungsplatz'),
        ),
        migrations.CreateModel(
            name='BewerberWunschberuf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausbildungsberuf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ausbildungsberuf')),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bewerber')),
            ],
            options={
                'unique_together': {('bewerber', 'ausbildungsberuf')},
            },
        ),
    ]
