# Generated by Django 5.2.8 on 2025-11-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerber',
            name='wunschberufe',
            field=models.ManyToManyField(related_name='bewerber', to='main.ausbildungsberuf'),
        ),
    ]
