# Generated by Django 5.2.8 on 2025-11-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bewerber_wunschberufe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BewerberWunschberuf',
        ),
    ]
