# Generated by Django 5.2.8 on 2025-11-26 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_bewerberwunschberuf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bewerber',
            name='wunschberufe',
        ),
        migrations.AddField(
            model_name='bewerber',
            name='wunschberuf_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.ausbildungsberuf'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='wunschberuf_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.ausbildungsberuf'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='wunschberuf_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.ausbildungsberuf'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='wunschberuf_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.ausbildungsberuf'),
        ),
    ]
